name: Deploy to GitHub Pages

on:
  push:
    branches: [ deploy ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Voxel2Pixel.sln

    - name: Build
      run: dotnet build Voxel2Pixel.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish Voxel2Pixel.Web/Voxel2Pixel.Web.csproj -c Release -o release --nologo

    # Changes the base tag in index.html from '/' to '/Voxel2Pixel/' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/Voxel2Pixel\/" \/>/g' release/wwwroot/index.html

    # Add .nojekyll file to tell GitHub pages not to run Jekyll processing
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'release/wwwroot'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
